Added patch envelope support
zededa/terraform-provider-zedcloud pull request #101
Opened 2023-12-28 11:13 UTC by shrikanthb-zededa

Added support to manage patch envelope through Zededa terraform provider.
Auto generated client, models, schemas files for patch envelope from the latest app_instance swagger.json file. Added resources file for patch envelope operations. Made necessary changes to auto generated files for it to work with resources file.
It supports creating/updating patch envelopes and attaching/detaching it from app instance.
Added test case for patch envelope management through terraform-provider. 
Updated documentation to include the patch envelope resources and data-sources files.
Formatted main.tf with `terraform fmt`.

2024-01-08 14:00 UTC, xyuria-zededa requested changes
Added a couple of comments. Please take a look when you have time.

2024-01-08 14:00 UTC, xyuria-zededa commented on resources/patch_envelope.go
> +	if errs := readPatchEnvelopeByName(ctx, d, m); err != nil {
It's better to rewrite this code as the following:
`if diags := readPatchEnvelopeByName(ctx, d, m); diags.HasError() {
		return diags
	}`
The reason is that the variable err doesn't belong to this scope and  doesn't check correctness of the readPathEnvelopeByName response.

2024-01-08 14:00 UTC, xyuria-zededa commented on resources/patch_envelope.go
> +	if errs := readPatchEnvelopeByName(ctx, d, m); err != nil {
The code better be rewritten as mentioned in the comment for CreatePathEnvelope function.

2024-01-08 14:00 UTC, xyuria-zededa commented on resources/patch_reference_update.go
> +	if errs := readPatchEnvelopeByName(ctx, d, m); err != nil {
It's better to rewrite this code as the following:
`if diags := readPatchEnvelopeByName(ctx, d, m); diags.HasError() {
		return diags
	}`
The reason is that the variable err doesn't belong to this scope and  doesn't check correctness of the readPathEnvelopeByName response.

2024-01-08 14:00 UTC, xyuria-zededa commented on resources/utils/helper_functions.go
> +func Remove(s []string, r string) []string {
Do we use this helper function somewhere? If not, please remove it.

2024-01-08 14:00 UTC, xyuria-zededa commented on main.tf
> +      image_id = resource.zedcloud_image.test_tf_provider.id
Here and below we don't need to use 'resource' when specifying a dependency. Just `zedcloud_image.test_tf_provider.id`. Please correct it when you have time.

2024-01-09 09:19 UTC, shrikanthb-zededa commented on resources/patch_envelope.go
> +	if errs := readPatchEnvelopeByName(ctx, d, m); err != nil {
updated.

2024-01-09 09:19 UTC, shrikanthb-zededa commented on resources/patch_envelope.go
> +	if errs := readPatchEnvelopeByName(ctx, d, m); err != nil {
updated.

2024-01-09 09:20 UTC, shrikanthb-zededa commented on resources/patch_reference_update.go
> +	if errs := readPatchEnvelopeByName(ctx, d, m); err != nil {
removed reading patch envelope after updating patch envelope reference as it is not useful.

2024-01-09 09:20 UTC, shrikanthb-zededa commented on resources/utils/helper_functions.go
> +func Remove(s []string, r string) []string {
removed it

2024-01-09 09:20 UTC, shrikanthb-zededa commented on main.tf
> +      image_id = resource.zedcloud_image.test_tf_provider.id
corrected it

2024-01-09 13:00 UTC, xyuria-zededa approved these changes
LGTM

2024-01-10 06:01 UTC, merged